[package]
name = "data"
version = "0.1.0"
authors = ["Amr Hassan <amr.hassan@gmail.com>"]
edition = "2018"

[dependencies]
ordered-float = "1.0.2"
thrift = "0.12.0"
try_from = "0.3.2"
clap = {version = "2.33", features = ["yaml"]}